server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          jws-algorithms: RS512
#          public-key-location: classpath:certs/publicKey.txt
          jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs